#===============================================================================
# Home Assistant Main Configuration
# File: configuration.yaml
# Updated: 2025-08-22
# Note: Sensors moved to packages/integration_sensors.yaml
#===============================================================================
# Loads default set of integrations. Do not remove.
default_config:
#-------------------------------------------------------------------------------
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
#-------------------------------------------------------------------------------
# Text to speech default config
tts:
  - platform: google_translate  
    service_name: google_say

#-------------------------------------------------------------------------------  



#-------------------------------------------------------------------------------
# Enable the recorder for long-term statistics (works with InfluxDB)
# Recorder Configuration - Optimized for Performance and Storage
recorder:
  # Extended retention for better trend analysis (optimal for your 2x8kW setup)
  purge_keep_days: 30
  auto_purge: true
  auto_repack: true
  
  # Optimized commit interval for better performance with InfluxDB
  commit_interval: 5
  
  # Strategic domain inclusion - be selective
  include:
    domains:
      - climate
      - person
      - device_tracker
      - automation
      - script
      - light
      - switch
    entities:
      # Include only critical sensors for your energy monitoring
      - sensor.deyeinvertermaster_summary_battery_soc
      - sensor.deyeinverterslave_summary_battery_soc
      - sensor.deyeinvertermaster_today_energy_bought
      - sensor.deyeinvertermaster_today_energy_sold
      - sensor.deyeinvertermaster_today_load_consumption
      - sensor.deyeinverterslave_today_energy_bought
      - sensor.deyeinverterslave_today_energy_sold
      - sensor.deyeinverterslave_today_load_consumption
      - sensor.deyeinvertermaster_ac_output_active_power_r_total
      - sensor.deyeinverterslave_ac_output_active_power_r_total

  # Comprehensive exclusions for high-frequency, low-value entities  
  exclude:
    domains:
      - updater
      - sun
    entities:
      # Time and date sensors (change constantly, no historical value)
      - sensor.date_time
      - sensor.time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.uptime
      - sensor.time_utc
      
      # System sensors that change frequently
      - sensor.last_boot
      - sensor.processor_use
      - sensor.processor_temperature
      - sensor.memory_use_percent
      - sensor.swap_use_percent
      - sensor.load_1m
      - sensor.load_5m 
      - sensor.load_15m
      
      # Network monitoring sensors (if you have them)
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      
      # Frequent automation state changes
      - automation.daily_sensor_report_09h00_final
      - automation.extract_sensors_daily
      
    # Wildcard patterns go in entity_globs (NOT entities)
    entity_globs:
      # Exclude all HACS and update sensors (frequent changes, low value)
      - sensor.*_update_available
      - sensor.hacs_*
      - binary_sensor.hacs_*
      
      # Exclude weather API sensors that update frequently
      - sensor.openweathermap_*
      - sensor.weather_*
      
      # Exclude frequent changing device trackers from unknown devices
      - device_tracker.unknown_*
      
      # Exclude frequent node-red status entities
      - sensor.node_red_*
      
      # Exclude telegram notification history
      - sensor.telegram_*
#-------------------------------------------------------------------------------
# Logger configuration for debugging
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.tuya: info
    custom_components: info
    homeassistant.core: info
    homeassistant.components.automation: info
    homeassistant.components.script: info

#-------------------------------------------------------------------------------
# HTTP Configuration - Secure and Optimized (Corrected)
http:
  # Core security settings
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 127.0.0.1
    - ::1
  
  # CORS configuration for your static IP and local access
  cors_allowed_origins:
    - "https://192.168.1.30:8123"
    - "http://192.168.1.30:8123"
    - "http://localhost:8123"
    - "http://127.0.0.1:8123"
    - "https://my.home-assistant.io"  # For HA Cloud if using remote access
  
  # Security settings optimized for your setup
  login_attempts_threshold: 5      # Reduced from 10 for better security
  ip_ban_enabled: true
  use_x_frame_options: true        # CRITICAL: Changed to true for security
  
  # SSL profile for better security
  ssl_profile: modern
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
group: !include groups.yaml

# Packages Configuration - Load all packages
homeassistant: 
  packages: !include_dir_named packages
  
  # Enhanced packages configuration
  name: "Smart Home - Pierre van Ryneveld"
  latitude: -25.84051
  longitude: 28.24814
  elevation: 1519
  unit_system: metric
  time_zone: Africa/Johannesburg
  country: ZA
  currency: ZAR
  allowlist_external_dirs:
    - "/config/sensor_reports"
    - "/tmp"


#-------------------------------------------------------------------------------
 # Shell Commands
shell_command:
  git_commit: '/config/scripts/git_commit.sh'
  
  # Remove problematic exports (commented out - good!)
  # export_sensor_list: >
  #   bash -c "hass-cli entity list | grep ^sensor."
  
  # Secure version using secrets
  restart_deye_integration: >
    curl -X POST -H "Authorization: Bearer !secret ha_long_lived_token" \
    -H "Content-Type: application/json" \
    http://localhost:8123/api/config/config_entries/reload
    
  backup_config: >
    cp -r /config /backup/ha-config-$(date +%Y%m%d_%H%M%S)
    
  extract_sensors: >
    python3 /config/scripts/extract_sensors.py
    
  check_system_status: >
    echo "System check at $(date)" > /config/system_check.log
    
  # Secure restart command using secrets
  restart_homeassistant: >
    curl -X POST -H "Authorization: Bearer !secret ha_long_lived_token" \
    -H "Content-Type: application/json" \
    http://localhost:8123/api/services/homeassistant/restart
#-------------------------------------------------------------------------------
input_number:
  battery_low_threshold:
    name: "Battery Low Threshold"
    min: 10
    max: 50
    step: 5
    initial: 20
    unit_of_measurement: "%"
    icon: mdi:battery-alert

  high_power_threshold:
    name: "High Power Usage Threshold"
    min: 1000
    max: 10000
    step: 100
    initial: 5000
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt

input_select:
  notification_priority:
    name: "Notification Priority Level"
    options:
      - "Low"
      - "Normal" 
      - "High"
      - "Critical"
    initial: "Normal"
    icon: mdi:priority-high

# Counter helpers for tracking
counter:
  daily_automations_triggered:
    name: "Daily Automations Triggered"
    icon: mdi:counter
    restore: false

  system_restarts:
    name: "System Restarts"
    icon: mdi:restart
    restore: true
#-------------------------------------------------------------------------------
