#===============================================================================
# Home Assistant Main Configuration
# File: configuration.yaml
# Updated: 2025-08-22
# Note: Sensors moved to packages/integration_sensors.yaml
#===============================================================================
# Loads default set of integrations. Do not remove.
default_config:
#-------------------------------------------------------------------------------
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
#-------------------------------------------------------------------------------
# Text to speech default config
tts:
  - platform: google_translate  
    service_name: google_say

#-------------------------------------------------------------------------------  



#-------------------------------------------------------------------------------
# Enable the recorder for long-term statistics (works with InfluxDB)
recorder:
  purge_keep_days: 10
  auto_purge: true
  auto_repack: true
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
      - climate
      - person
      - device_tracker
      - automation
      - script
  exclude:
    entities:
      - sensor.date_time
      - sensor.time
      - sensor.uptime
#-------------------------------------------------------------------------------
# History configuration
history:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
      - climate
      - automation
#-------------------------------------------------------------------------------
# Logger configuration for debugging
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.tuya: info
    custom_components: info
    homeassistant.core: info
    homeassistant.components.automation: info
    homeassistant.components.script: info

#-------------------------------------------------------------------------------
# HTTP configuration for external access
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24  
    - 127.0.0.1
# HTTP Configuration
  cors_allowed_origins:
    - "http://localhost"
    - "http://127.0.0.1"
    - "http://192.168.1.30:8123"
    - "https://192.168.1.30:8123"
  login_attempts_threshold: 10
  ip_ban_enabled: true
  use_x_frame_options: false    
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
group: !include groups.yaml

# Packages Configuration - Load all packages
homeassistant: 
  packages: !include_dir_named packages
  
  # Enhanced packages configuration
  name: "Smart Home - Pierre van Ryneveld"
  latitude: -25.7748
  longitude: 29.4696
  elevation: 1519
  unit_system: metric
  time_zone: Africa/Johannesburg
  country: ZA
  currency: ZAR
  allowlist_external_dirs:
    - "/config/sensor_reports"
    - "/tmp"


#-------------------------------------------------------------------------------
 # Shell Commands
shell_command:
  git_commit: '/config/scripts/git_commit.sh'
# Commented out, seem to be probematic  
#  export_sensor_list: >
#    bash -c "hass-cli entity list | grep ^sensor."
  restart_deye_integration: >
    curl -X POST -H "Authorization: Bearer YOUR_TOKEN" \
    -H "Content-Type: application/json" \
    http://localhost:8123/api/config/config_entries/reload
  backup_config: >
    cp -r /config /backup/ha-config-$(date +%Y%m%d_%H%M%S)  
  extract_sensors: >
    python3 /config/scripts/extract_sensors.py
  check_system_status: >
    echo "System check at $(date)" > /config/system_check.log
  restart_homeassistant: >
    curl -X POST -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkZWMzOTNlMWE3Mjc0ZTRmYTJkYjY2YmI3NDBlZjNjNiIsImlhdCI6MTc1NjcxNzY4MSwiZXhwIjoyMDcyMDc3NjgxfQ.Lw958tdXTVp23-EAh-36EjpeMV_jtB9cnX0_M3mTDl8" \
    -H "Content-Type: application/json" \
    http://localhost:8123/api/services/homeassistant/restart
#-------------------------------------------------------------------------------
input_number:
  battery_low_threshold:
    name: "Battery Low Threshold"
    min: 10
    max: 50
    step: 5
    initial: 20
    unit_of_measurement: "%"
    icon: mdi:battery-alert

  high_power_threshold:
    name: "High Power Usage Threshold"
    min: 1000
    max: 10000
    step: 100
    initial: 5000
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt

input_select:
  notification_priority:
    name: "Notification Priority Level"
    options:
      - "Low"
      - "Normal" 
      - "High"
      - "Critical"
    initial: "Normal"
    icon: mdi:priority-high

# Counter helpers for tracking
counter:
  daily_automations_triggered:
    name: "Daily Automations Triggered"
    icon: mdi:counter
    restore: false

  system_restarts:
    name: "System Restarts"
    icon: mdi:restart
    restore: true
#-------------------------------------------------------------------------------
