#===============================================================================
# Telegram Configuration
# Purpose: All Telegram service settings
#===============================================================================

# Enhanced Telegram Bot Configuration with error handling
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_bot_token
#    allowed_chat_ids:
#      - !secret telegram_chat_id
#    parse_mode: markdown  # Enables formatting
telegram_bot:
  - platform: polling
    api_key: 6968699549:AAHpWjA5SLFUd3Kk2CTtM838Vlhp8bTKZEU #your bot API KEY HERE
    allowed_chat_ids:
      - 6167623299 #your username chatid here as supplied by telegram
      - -1002014412698 #your chatgroup_for_bot chatid here, notice that groups start with minus


# Additional notification service for Telegram with options
notify:
  # Your existing email services...
  
  # Enhanced Telegram service
  - platform: telegram
    name: BarkieHome Solar #Eg user: Heinz or  solar: Solar
    chat_id: 6167623299 #your username chatid here as supplied by telegram
  - platform: telegram
    name: chatgroup_for_bot
    chat_id: -1002014412698 #your chatgroup for your bot chatid here as supplied by telegram, notice that groups start with minus

    # - platform: telegram
 #   name: telegram
 #   api_key: !secret telegram_bot_token
 #   chat_id: !secret telegram_chat_id
 #   
  # Telegram service with specific formatting
 # - platform: telegram
 #   name: telegram
 #   api_key: !secret telegram_bot_token
 #   chat_id: !secret telegram_chat_id
 #   parse_mode: markdown