# Enhanced Telegram Configuration
# Add this to your packages/notifications.yaml (merge with existing)

# Enhanced Telegram Bot Configuration with error handling
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - !secret telegram_chat_id
    parse_mode: markdown  # Enables formatting

# Additional notification service for Telegram with options
notify:
  # Your existing email services...
  
  # Enhanced Telegram service
  - platform: telegram
    name: telegram
    api_key: !secret telegram_bot_token
    chat_id: !secret telegram_chat_id
    
  # Telegram service with specific formatting
  - platform: telegram
    name: telegram
    api_key: !secret telegram_bot_token
    chat_id: !secret telegram_chat_id
    parse_mode: markdown

# Telegram-specific scripts with better formatting
script:
  # Your existing scripts...
  
  # Enhanced Telegram test
  telegram_connection_test:
    alias: "Telegram Connection Test"
    sequence:
      - service: notify.telegram_formatted
        data:
          title: "🔗 Connection Test"
          message: |
            *Home Assistant Telegram Test*
            
            📅 Date: {{ now().strftime('%Y-%m-%d') }}
            ⏰ Time: {{ now().strftime('%H:%M:%S') }}
            
            *System Information:*
            🖥️ Server: {{ states('sensor.johanba_server_status') | title }}
            🌡️ Temp: {{ states('sensor.johanba_server_system_temperature') }}°C
            💾 CPU: {{ states('sensor.johanba_server_cpu_usage') }}%
            
            *Network Status:*
            🌐 WAN: {{ 'Connected ✅' if is_state('binary_sensor.archer_d2_wan_status', 'on') else 'Disconnected ❌' }}
            
            If you can see this *formatted* message, your Telegram bot is `working perfectly`! 🎉
      - delay: 2
      - service: notify.telegram
        data:
          message: "✅ Telegram test completed successfully!"

# Telegram error detection automation
automation:
  # Your existing automations...
  
  - id: telegram_bot_offline_detection
    alias: "Telegram Bot Offline Detection"
    description: "Detect when Telegram bot goes offline"
    trigger:
      - platform: state
        entity_id: binary_sensor.telegram_bot_connected
        to: "off"
        for:
          minutes: 5
    action:
      - service: notify.email_ha
        data:
          title: "⚠️ Telegram Bot Offline"
          message: |
            Telegram Bot Connection Lost
            
            The Telegram bot has been offline for 5+ minutes.
            
            Please check:
            1. Internet connection
            2. Bot token in secrets.yaml
            3. Chat ID configuration
            4. Telegram service status
            
            Time: {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
            
            This notification was sent via email as backup.

  # Enhanced daily Telegram test
  - id: telegram_daily_enhanced_test
    alias: "Telegram Daily Enhanced Test"
    description: "Enhanced daily Telegram test with more info"
    trigger:
      - platform: time
        at: "09:00:30"  # Slightly after email test
    condition: []
    action:
      - service: notify.telegram_formatted
        data:
          title: "🌅 Daily Status"
          message: |
            *Good Morning! Daily Home Assistant Report*
            
            📅 {{ now().strftime('%A, %B %d, %Y') }}
            ⏰ {{ now().strftime('%H:%M:%S') }}
            
            *🖥️ System Health:*
            • Status: {{ states('sensor.johanba_server_status') | title }} {{ '✅' if states('sensor.johanba_server_status') == 'good' else '⚠️' }}
            • Temperature: {{ states('sensor.johanba_server_system_temperature') }}°C
            • CPU Usage: {{ states('sensor.johanba_server_cpu_usage') }}%
            • Memory: {{ states('sensor.johanba_server_memory_usage') }}%
            
            *☁️ OneDrive Status:*
            • Storage: {{ states('sensor.onedrive_usage_percentage') }}% used
            • Drive State: {{ states('sensor.onedrive_drive_state') | title }}
            
            *🌐 Network:*
            • Connection: {{ 'Online ✅' if is_state('binary_sensor.archer_d2_wan_status', 'on') else 'Offline ❌' }}
            • External IP: `{{ states('sensor.archer_d2_external_ip') }}`
            
            *📊 Add-ons Running:*
            • File Editor: {{ '✅' if is_state('binary_sensor.file_editor_running', 'on') else '❌' }}
            • Code Server: {{ '✅' if is_state('binary_sensor.studio_code_server_running', 'on') else '❌' }}
            • Terminal: {{ '✅' if is_state('binary_sensor.terminal_ssh_running', 'on') else '❌' }}
            
            Have a great day! 🎉
            
            _Automated message from Home Assistant_